---
extends:
  - standard
  - plugin:import/recommended
  - plugin:import/typescript # this line does the trick

# or configure manually:
plugins:
  - import
  - promise
  - standard
  - "@typescript-eslint"

parser: "@typescript-eslint/parser"

parserOptions:
  sourceType: module
  ecmaVersion: 6

rules:
  comma-dangle: off
  #  "import/order": ["error", {"groups": ["index", "sibling", "parent", "internal", "external", "builtin"]}]
  "import/order": "error"
  "import/no-unused-modules": [1, { "unusedExports": true }]
  "no-unused-vars": "off"
  "@typescript-eslint/no-unused-vars": ["error"]
