name: ci

on:
  push:
    branches-ignore:
      - gh-pages
      - 'renovate/**'
    tags:
      - 'v*'
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13, 14]
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        with:
          path: ./node_modules
          key: node-${{ hashFiles('package-lock.json') }}

      - run: npm ci
        if: steps.cache-primes.outputs.cache-hit != 'true'

      - run: npm run lint

      - run: npm run build

      - name: Preview
        if: ${{ (matrix.node-version == '14') && (github.ref == 'refs/heads/master') }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          commit_message: deploy ${{ github.ref }}
          force_orphan: true
          publish_branch: preview

  dist:
    runs-on: ubuntu-latest
    needs: main
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - uses: actions/cache@v2
        with:
          path: ./node_modules
          key: node-${{ hashFiles('package-lock.json') }}

      - run: npm ci
        if: steps.cache-primes.outputs.cache-hit != 'true'

      - run: npm run build

      - run: |
          sudo apt-get install tree -y
          tree -H '.' -L 1 --noreport --charset utf-8 ./dist | tee dist/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          commit_message: deploy ${{ github.ref }}
